# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0558e49405c05f4e0da1907bd81e8f0ae1d9af5554b258e3ac9aab698b6af5fd25a892fbbe6387b277d7b3128cd69b82a2f3c696e26e86790db1d0c774f4ab5

test:
  secret_key_base: 03ad10547f78d2dd75ae690bb66b065c30202851eb16014f9fdea2bd5db7564eca254aaa6a4c06717f336503a933cfe95872eb6a785f0502542c2fa9227a2077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
